#!/bin/sh
# startsyslog - Start syslogd and show logging messages
# (C) Klaus Knopper Jun 2001

PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export PATH

TITLE="IPTRAF"

RXVT=""
[ -n "$DISPLAY" ] && RXVT="rxvt -T $TITLE -bg black -fg green -cr red -e"
[ "`id -u`" != "0" ] && exec $RXVT kanotix-su "$0" "$@"

iptraf

exit 0

